//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISS_WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutboundOrders
    {
        public int OutboundOrderId { get; set; }
        public int OrderId { get; set; }
        public int WarehouseId { get; set; }
        public System.DateTime ShippedDate { get; set; }
        public int ShippedByUserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Users Users { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
