//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISS_WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthority
    {
        public string EmployeeNo { get; set; }
        public string ProgramsID { get; set; }
        public Nullable<bool> Run { get; set; }
        public Nullable<bool> Append { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> Report { get; set; }
    
        public virtual Programs Programs { get; set; }
        public virtual XINUser XINUser { get; set; }
    }
}
